/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_cognito_identity_pool_id": "us-east-1:b716db8e-94d8-437a-b33b-f64bbe8d378c",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_zaxnzne2N",
  "aws_user_pools_web_client_id": "6fs99j4n6vsgumrg76kn8lhi97",
  "oauth": {},
  "aws_cognito_username_attributes": [
      "EMAIL"
  ],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
      "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
      "SMS"
  ],
  "aws_cognito_password_protection_settings": {
      "passwordPolicyMinLength": 8,
      "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
      "EMAIL"
  ],
  "Auth": {
      "region": "us-east-1",
      "userPoolId": "us-east-1_hHFOqKWKp",
      "userPoolWebClientId": "724d6dphosr5k9ef1aq7ktb5vd"
  }
};


export default awsmobile;
